logging:
  config: classpath:config/log4j2.xml
spring:
  application:
    name: spring-boot-elasticsearch
elasticsearch:
  rest-url: http://192.168.41.128:9200
  ips: 192.168.41.128
  pool-size: 50
  cluster:
    name: elasticsearch
  tcp:
    port: 9300