logging:
  config: classpath:config/log4j2.xml
spring:
  application:
    name: spring-boot-lettuce
  redis:
    host: 192.168.41.128
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
