logging:
  config: classpath:config/log4j2.xml
spring:
  application:
    name: spring-security-demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: tKzRFGdS5hs=
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1               #初始化连接数量
      max-active: 10              #连接池再同一时间能够分配的最大活动连接的数量
      min-idle: 1                   #连接池中容许保持空闲状态的最小连接数量
      max-wait: 5000                #连接池等待连接被归还的最大时间
      time-between-eviction-runs-millis: 300000      #在空闲连接回收器线程运行期间休眠的时间值
      min-evictable-idle-time-millis: 3000000        #连接在池中保持空闲而不被空闲连接回收器线程(如果有)回收的最小时间值
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      pool-prepared-statements: true
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: classpath*:org/hiphone/mybatis/entitys/*
server:
  port: 8082